services:
  api:
    container_name: ckb-api
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn prod:api
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=api_db
    depends_on:
      - api_db
#    volumes:
#      - mono-node-modules:/app/node_modules
    networks:
      - ckb-network

  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ckb-core
    command: yarn prod:core
    depends_on:
      - api
#    environment:
#      - API_URL=http://bestsvetny.com/api
#      - BOARD_HOST_URL=http://bestsvetny.com/board/api
#      - CHAT_HOST_URL=http://bestsvetny.com/chat/api
#    volumes:
#      - mono-node-modules:/app/node_modules
    networks:
      - ckb-network

  nginx:
    image: nginx:stable-alpine
    container_name: ckb-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - core
      - api
    networks:
      - ckb-network

  api_db:
    container_name: ckb-api-db
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=squeezer
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - ckb-network
    secrets:
      - db_password

volumes:
  postgres_data_local:
#  mono-node-modules:
#  ^ fix NX caches

secrets:
  db_password:
    file: db_password.txt

networks:
  ckb-network:
    driver: bridge
