name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
        env:
          API_URL: ${{ vars.API_URL }}
          BOARD_HOST_URL: ${{ vars.BOARD_HOST_URL }}
          CHAT_HOST_URL: ${{ vars.CHAT_HOST_URL }}
          API_PORT: ${{ vars.API_PORT }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_HOST: ${{ vars.CHAT_HOST_URL }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
